services:
  web-app:
    build:
      context: .  #path the location where has dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service #chotbi ne rebuldit ete unenqw python code poxac rebuild chenqn dockeri mej local papken miacrinq dockerin
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass