# Generated by Django 3.2.16 on 2023-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
