# Generated by Django 3.2.16 on 2023-11-06 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='field_a',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='field_b',
            field=models.CharField(default=datetime.datetime(2023, 11, 6, 18, 20, 22, 309944, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['field_a', 'field_b'], name='services_su_field_a_155836_idx'),
        ),
    ]
